
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Sep 28 13:48:41 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 40;
  public static final int MAP = 27;
  public static final int LBRACKET = 9;
  public static final int INCREMENT = 23;
  public static final int CONST = 5;
  public static final int NUMCONST = 45;
  public static final int NOT_EQUAL = 31;
  public static final int LPAREN = 12;
  public static final int GREATER = 34;
  public static final int CONTINUE = 17;
  public static final int TAR = 29;
  public static final int MINUS = 38;
  public static final int LESS = 36;
  public static final int DECREMENT = 24;
  public static final int RPAREN = 13;
  public static final int SEMICOLON = 8;
  public static final int AND = 26;
  public static final int OR = 25;
  public static final int COMMA = 7;
  public static final int LESS_EQUAL = 35;
  public static final int MULTIPLY = 39;
  public static final int PLUS = 37;
  public static final int IF = 14;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 6;
  public static final int GREATER_EQUAL = 33;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MOD = 41;
  public static final int IDENT = 43;
  public static final int BREAK = 16;
  public static final int VOID = 11;
  public static final int UNION = 42;
  public static final int LBRACE = 3;
  public static final int ELSE = 15;
  public static final int READ = 19;
  public static final int CHARCONST = 44;
  public static final int FINAL = 30;
  public static final int WHILE = 22;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 46;
  public static final int PROG = 2;
  public static final int EQUAL_EQUAL = 32;
  public static final int PRINT = 20;
  public static final int DO = 21;
}

